# Definir tipo de base de datos
quarkus.datasource.db-kind=postgresql

quarkus.datasource.username=postgres
quarkus.datasource.password=d011175
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pa2db

# Sincronizar mi codigo con la base de datos
# update sincroniza cuando hay cambio
quarkus.hibernate-orm.database.generation=update
# Mostrar la consulta sql
quarkus.hibernate-orm.log.sql=true

quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.type.descriptor.sql".level=TRACE
quarkus.transaction-manager.default-transaction-timeout=PT240S